/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Visual;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author TheYazanagi
 */
public class fjfPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form fjfPrincipal
     */
    public fjfPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlTitulo = new javax.swing.JLabel();
        jlSubTitulo = new javax.swing.JLabel();
        jmbBarraMenu = new javax.swing.JMenuBar();
        jmClientes = new javax.swing.JMenu();
        jmiCadastrarClientes = new javax.swing.JMenuItem();
        jmPesquisarClientes = new javax.swing.JMenuItem();
        jmProdutos = new javax.swing.JMenu();
        jmiCadastrarProdutos = new javax.swing.JMenuItem();
        jmiPesquisarProdutos = new javax.swing.JMenuItem();
        jmPedidos = new javax.swing.JMenu();
        jmiCriarPedidos = new javax.swing.JMenuItem();
        jmiPesquisarPedidos = new javax.swing.JMenuItem();
        jmOpções = new javax.swing.JMenu();
        jmiSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home");

        jlTitulo.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jlTitulo.setText("Auto-peças");

        jlSubTitulo.setText("Projeto Grupo05");

        jmClientes.setText("Clientes");

        jmiCadastrarClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.CTRL_MASK));
        jmiCadastrarClientes.setText("Cadastrar");
        jmiCadastrarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCadastrarClientesActionPerformed(evt);
            }
        });
        jmClientes.add(jmiCadastrarClientes);

        jmPesquisarClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, java.awt.event.InputEvent.CTRL_MASK));
        jmPesquisarClientes.setText("Pesquisar/excluir");
        jmPesquisarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmPesquisarClientesActionPerformed(evt);
            }
        });
        jmClientes.add(jmPesquisarClientes);

        jmbBarraMenu.add(jmClientes);

        jmProdutos.setText("Produtos");

        jmiCadastrarProdutos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, java.awt.event.InputEvent.CTRL_MASK));
        jmiCadastrarProdutos.setText("Cadastrar");
        jmiCadastrarProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCadastrarProdutosActionPerformed(evt);
            }
        });
        jmProdutos.add(jmiCadastrarProdutos);

        jmiPesquisarProdutos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, java.awt.event.InputEvent.CTRL_MASK));
        jmiPesquisarProdutos.setText("Pesquisar/Excluir");
        jmProdutos.add(jmiPesquisarProdutos);

        jmbBarraMenu.add(jmProdutos);

        jmPedidos.setText("Pedidos");

        jmiCriarPedidos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F9, java.awt.event.InputEvent.CTRL_MASK));
        jmiCriarPedidos.setText("Criar");
        jmPedidos.add(jmiCriarPedidos);

        jmiPesquisarPedidos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F10, java.awt.event.InputEvent.CTRL_MASK));
        jmiPesquisarPedidos.setText("Pesquisar");
        jmPedidos.add(jmiPesquisarPedidos);

        jmbBarraMenu.add(jmPedidos);

        jmOpções.setText("Opções");

        jmiSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
        jmiSair.setText("Sair");
        jmiSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSairActionPerformed(evt);
            }
        });
        jmOpções.add(jmiSair);

        jmbBarraMenu.add(jmOpções);

        setJMenuBar(jmbBarraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(273, 273, 273)
                        .addComponent(jlSubTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(jlTitulo)))
                .addContainerGap(257, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jlTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlSubTitulo)
                .addContainerGap(400, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jmiSairActionPerformed

    private void jmiCadastrarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCadastrarClientesActionPerformed
        fjfCadastroClientes form = null;
        try {
            form = new fjfCadastroClientes();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(fjfPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        form.setVisible(true);
    }//GEN-LAST:event_jmiCadastrarClientesActionPerformed

    private void jmPesquisarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmPesquisarClientesActionPerformed
        fjfBuscaClientes form = null;
        form = new fjfBuscaClientes();
        form.setVisible(true);
    }//GEN-LAST:event_jmPesquisarClientesActionPerformed

    private void jmiCadastrarProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCadastrarProdutosActionPerformed
        fjfCadastroProdutos form = null;
        try {
            form = new fjfCadastroProdutos();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(fjfPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        form.setVisible(true);
    }//GEN-LAST:event_jmiCadastrarProdutosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fjfPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fjfPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fjfPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fjfPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fjfPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlSubTitulo;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JMenu jmClientes;
    private javax.swing.JMenu jmOpções;
    private javax.swing.JMenu jmPedidos;
    private javax.swing.JMenuItem jmPesquisarClientes;
    private javax.swing.JMenu jmProdutos;
    private javax.swing.JMenuBar jmbBarraMenu;
    private javax.swing.JMenuItem jmiCadastrarClientes;
    private javax.swing.JMenuItem jmiCadastrarProdutos;
    private javax.swing.JMenuItem jmiCriarPedidos;
    private javax.swing.JMenuItem jmiPesquisarPedidos;
    private javax.swing.JMenuItem jmiPesquisarProdutos;
    private javax.swing.JMenuItem jmiSair;
    // End of variables declaration//GEN-END:variables
}
